dist: focal
sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jedirichang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jedirichang/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-615299754589"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECERET_KEY"